// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"user/internal/ent/carts"
)

// CartsCreate is the builder for creating a Carts entity.
type CartsCreate struct {
	config
	mutation *CartsMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCartID sets the "cart_id" field.
func (_c *CartsCreate) SetCartID(v int64) *CartsCreate {
	_c.mutation.SetCartID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CartsCreate) SetUserID(v int64) *CartsCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *CartsCreate) SetProductID(v int64) *CartsCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *CartsCreate) SetQuantity(v int) *CartsCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_c *CartsCreate) SetNillableQuantity(v *int) *CartsCreate {
	if v != nil {
		_c.SetQuantity(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CartsCreate) SetStatus(v int) *CartsCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CartsCreate) SetNillableStatus(v *int) *CartsCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCompanyID sets the "company_id" field.
func (_c *CartsCreate) SetCompanyID(v int64) *CartsCreate {
	_c.mutation.SetCompanyID(v)
	return _c
}

// SetCompanyName sets the "company_name" field.
func (_c *CartsCreate) SetCompanyName(v string) *CartsCreate {
	_c.mutation.SetCompanyName(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CartsCreate) SetCreatedAt(v time.Time) *CartsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CartsCreate) SetNillableCreatedAt(v *time.Time) *CartsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CartsCreate) SetUpdatedAt(v time.Time) *CartsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CartsCreate) SetNillableUpdatedAt(v *time.Time) *CartsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the CartsMutation object of the builder.
func (_c *CartsCreate) Mutation() *CartsMutation {
	return _c.mutation
}

// Save creates the Carts in the database.
func (_c *CartsCreate) Save(ctx context.Context) (*Carts, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CartsCreate) SaveX(ctx context.Context) *Carts {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CartsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CartsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CartsCreate) defaults() {
	if _, ok := _c.mutation.Quantity(); !ok {
		v := carts.DefaultQuantity
		_c.mutation.SetQuantity(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := carts.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CartsCreate) check() error {
	if _, ok := _c.mutation.CartID(); !ok {
		return &ValidationError{Name: "cart_id", err: errors.New(`ent: missing required field "Carts.cart_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Carts.user_id"`)}
	}
	if _, ok := _c.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "Carts.product_id"`)}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "Carts.quantity"`)}
	}
	if _, ok := _c.mutation.CompanyID(); !ok {
		return &ValidationError{Name: "company_id", err: errors.New(`ent: missing required field "Carts.company_id"`)}
	}
	if _, ok := _c.mutation.CompanyName(); !ok {
		return &ValidationError{Name: "company_name", err: errors.New(`ent: missing required field "Carts.company_name"`)}
	}
	if v, ok := _c.mutation.CompanyName(); ok {
		if err := carts.CompanyNameValidator(v); err != nil {
			return &ValidationError{Name: "company_name", err: fmt.Errorf(`ent: validator failed for field "Carts.company_name": %w`, err)}
		}
	}
	return nil
}

func (_c *CartsCreate) sqlSave(ctx context.Context) (*Carts, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CartsCreate) createSpec() (*Carts, *sqlgraph.CreateSpec) {
	var (
		_node = &Carts{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(carts.Table, sqlgraph.NewFieldSpec(carts.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CartID(); ok {
		_spec.SetField(carts.FieldCartID, field.TypeInt64, value)
		_node.CartID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(carts.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ProductID(); ok {
		_spec.SetField(carts.FieldProductID, field.TypeInt64, value)
		_node.ProductID = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(carts.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(carts.FieldStatus, field.TypeInt, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CompanyID(); ok {
		_spec.SetField(carts.FieldCompanyID, field.TypeInt64, value)
		_node.CompanyID = value
	}
	if value, ok := _c.mutation.CompanyName(); ok {
		_spec.SetField(carts.FieldCompanyName, field.TypeString, value)
		_node.CompanyName = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(carts.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(carts.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Carts.Create().
//		SetCartID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CartsUpsert) {
//			SetCartID(v+v).
//		}).
//		Exec(ctx)
func (_c *CartsCreate) OnConflict(opts ...sql.ConflictOption) *CartsUpsertOne {
	_c.conflict = opts
	return &CartsUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Carts.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CartsCreate) OnConflictColumns(columns ...string) *CartsUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CartsUpsertOne{
		create: _c,
	}
}

type (
	// CartsUpsertOne is the builder for "upsert"-ing
	//  one Carts node.
	CartsUpsertOne struct {
		create *CartsCreate
	}

	// CartsUpsert is the "OnConflict" setter.
	CartsUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *CartsUpsert) SetUserID(v int64) *CartsUpsert {
	u.Set(carts.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CartsUpsert) UpdateUserID() *CartsUpsert {
	u.SetExcluded(carts.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *CartsUpsert) AddUserID(v int64) *CartsUpsert {
	u.Add(carts.FieldUserID, v)
	return u
}

// SetProductID sets the "product_id" field.
func (u *CartsUpsert) SetProductID(v int64) *CartsUpsert {
	u.Set(carts.FieldProductID, v)
	return u
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *CartsUpsert) UpdateProductID() *CartsUpsert {
	u.SetExcluded(carts.FieldProductID)
	return u
}

// AddProductID adds v to the "product_id" field.
func (u *CartsUpsert) AddProductID(v int64) *CartsUpsert {
	u.Add(carts.FieldProductID, v)
	return u
}

// SetQuantity sets the "quantity" field.
func (u *CartsUpsert) SetQuantity(v int) *CartsUpsert {
	u.Set(carts.FieldQuantity, v)
	return u
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *CartsUpsert) UpdateQuantity() *CartsUpsert {
	u.SetExcluded(carts.FieldQuantity)
	return u
}

// AddQuantity adds v to the "quantity" field.
func (u *CartsUpsert) AddQuantity(v int) *CartsUpsert {
	u.Add(carts.FieldQuantity, v)
	return u
}

// SetStatus sets the "status" field.
func (u *CartsUpsert) SetStatus(v int) *CartsUpsert {
	u.Set(carts.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CartsUpsert) UpdateStatus() *CartsUpsert {
	u.SetExcluded(carts.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *CartsUpsert) AddStatus(v int) *CartsUpsert {
	u.Add(carts.FieldStatus, v)
	return u
}

// ClearStatus clears the value of the "status" field.
func (u *CartsUpsert) ClearStatus() *CartsUpsert {
	u.SetNull(carts.FieldStatus)
	return u
}

// SetCompanyID sets the "company_id" field.
func (u *CartsUpsert) SetCompanyID(v int64) *CartsUpsert {
	u.Set(carts.FieldCompanyID, v)
	return u
}

// UpdateCompanyID sets the "company_id" field to the value that was provided on create.
func (u *CartsUpsert) UpdateCompanyID() *CartsUpsert {
	u.SetExcluded(carts.FieldCompanyID)
	return u
}

// AddCompanyID adds v to the "company_id" field.
func (u *CartsUpsert) AddCompanyID(v int64) *CartsUpsert {
	u.Add(carts.FieldCompanyID, v)
	return u
}

// SetCompanyName sets the "company_name" field.
func (u *CartsUpsert) SetCompanyName(v string) *CartsUpsert {
	u.Set(carts.FieldCompanyName, v)
	return u
}

// UpdateCompanyName sets the "company_name" field to the value that was provided on create.
func (u *CartsUpsert) UpdateCompanyName() *CartsUpsert {
	u.SetExcluded(carts.FieldCompanyName)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CartsUpsert) SetCreatedAt(v time.Time) *CartsUpsert {
	u.Set(carts.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CartsUpsert) UpdateCreatedAt() *CartsUpsert {
	u.SetExcluded(carts.FieldCreatedAt)
	return u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *CartsUpsert) ClearCreatedAt() *CartsUpsert {
	u.SetNull(carts.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CartsUpsert) SetUpdatedAt(v time.Time) *CartsUpsert {
	u.Set(carts.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CartsUpsert) UpdateUpdatedAt() *CartsUpsert {
	u.SetExcluded(carts.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *CartsUpsert) ClearUpdatedAt() *CartsUpsert {
	u.SetNull(carts.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Carts.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CartsUpsertOne) UpdateNewValues() *CartsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CartID(); exists {
			s.SetIgnore(carts.FieldCartID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Carts.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CartsUpsertOne) Ignore() *CartsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CartsUpsertOne) DoNothing() *CartsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CartsCreate.OnConflict
// documentation for more info.
func (u *CartsUpsertOne) Update(set func(*CartsUpsert)) *CartsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CartsUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CartsUpsertOne) SetUserID(v int64) *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CartsUpsertOne) AddUserID(v int64) *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CartsUpsertOne) UpdateUserID() *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.UpdateUserID()
	})
}

// SetProductID sets the "product_id" field.
func (u *CartsUpsertOne) SetProductID(v int64) *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.SetProductID(v)
	})
}

// AddProductID adds v to the "product_id" field.
func (u *CartsUpsertOne) AddProductID(v int64) *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.AddProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *CartsUpsertOne) UpdateProductID() *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.UpdateProductID()
	})
}

// SetQuantity sets the "quantity" field.
func (u *CartsUpsertOne) SetQuantity(v int) *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *CartsUpsertOne) AddQuantity(v int) *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *CartsUpsertOne) UpdateQuantity() *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.UpdateQuantity()
	})
}

// SetStatus sets the "status" field.
func (u *CartsUpsertOne) SetStatus(v int) *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *CartsUpsertOne) AddStatus(v int) *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CartsUpsertOne) UpdateStatus() *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *CartsUpsertOne) ClearStatus() *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.ClearStatus()
	})
}

// SetCompanyID sets the "company_id" field.
func (u *CartsUpsertOne) SetCompanyID(v int64) *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.SetCompanyID(v)
	})
}

// AddCompanyID adds v to the "company_id" field.
func (u *CartsUpsertOne) AddCompanyID(v int64) *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.AddCompanyID(v)
	})
}

// UpdateCompanyID sets the "company_id" field to the value that was provided on create.
func (u *CartsUpsertOne) UpdateCompanyID() *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.UpdateCompanyID()
	})
}

// SetCompanyName sets the "company_name" field.
func (u *CartsUpsertOne) SetCompanyName(v string) *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.SetCompanyName(v)
	})
}

// UpdateCompanyName sets the "company_name" field to the value that was provided on create.
func (u *CartsUpsertOne) UpdateCompanyName() *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.UpdateCompanyName()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CartsUpsertOne) SetCreatedAt(v time.Time) *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CartsUpsertOne) UpdateCreatedAt() *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *CartsUpsertOne) ClearCreatedAt() *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.ClearCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CartsUpsertOne) SetUpdatedAt(v time.Time) *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CartsUpsertOne) UpdateUpdatedAt() *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *CartsUpsertOne) ClearUpdatedAt() *CartsUpsertOne {
	return u.Update(func(s *CartsUpsert) {
		s.ClearUpdatedAt()
	})
}

// Exec executes the query.
func (u *CartsUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CartsCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CartsUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CartsUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CartsUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CartsCreateBulk is the builder for creating many Carts entities in bulk.
type CartsCreateBulk struct {
	config
	err      error
	builders []*CartsCreate
	conflict []sql.ConflictOption
}

// Save creates the Carts entities in the database.
func (_c *CartsCreateBulk) Save(ctx context.Context) ([]*Carts, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Carts, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CartsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CartsCreateBulk) SaveX(ctx context.Context) []*Carts {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CartsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CartsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Carts.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CartsUpsert) {
//			SetCartID(v+v).
//		}).
//		Exec(ctx)
func (_c *CartsCreateBulk) OnConflict(opts ...sql.ConflictOption) *CartsUpsertBulk {
	_c.conflict = opts
	return &CartsUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Carts.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CartsCreateBulk) OnConflictColumns(columns ...string) *CartsUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CartsUpsertBulk{
		create: _c,
	}
}

// CartsUpsertBulk is the builder for "upsert"-ing
// a bulk of Carts nodes.
type CartsUpsertBulk struct {
	create *CartsCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Carts.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CartsUpsertBulk) UpdateNewValues() *CartsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CartID(); exists {
				s.SetIgnore(carts.FieldCartID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Carts.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CartsUpsertBulk) Ignore() *CartsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CartsUpsertBulk) DoNothing() *CartsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CartsCreateBulk.OnConflict
// documentation for more info.
func (u *CartsUpsertBulk) Update(set func(*CartsUpsert)) *CartsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CartsUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CartsUpsertBulk) SetUserID(v int64) *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CartsUpsertBulk) AddUserID(v int64) *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CartsUpsertBulk) UpdateUserID() *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.UpdateUserID()
	})
}

// SetProductID sets the "product_id" field.
func (u *CartsUpsertBulk) SetProductID(v int64) *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.SetProductID(v)
	})
}

// AddProductID adds v to the "product_id" field.
func (u *CartsUpsertBulk) AddProductID(v int64) *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.AddProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *CartsUpsertBulk) UpdateProductID() *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.UpdateProductID()
	})
}

// SetQuantity sets the "quantity" field.
func (u *CartsUpsertBulk) SetQuantity(v int) *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *CartsUpsertBulk) AddQuantity(v int) *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *CartsUpsertBulk) UpdateQuantity() *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.UpdateQuantity()
	})
}

// SetStatus sets the "status" field.
func (u *CartsUpsertBulk) SetStatus(v int) *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *CartsUpsertBulk) AddStatus(v int) *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CartsUpsertBulk) UpdateStatus() *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *CartsUpsertBulk) ClearStatus() *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.ClearStatus()
	})
}

// SetCompanyID sets the "company_id" field.
func (u *CartsUpsertBulk) SetCompanyID(v int64) *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.SetCompanyID(v)
	})
}

// AddCompanyID adds v to the "company_id" field.
func (u *CartsUpsertBulk) AddCompanyID(v int64) *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.AddCompanyID(v)
	})
}

// UpdateCompanyID sets the "company_id" field to the value that was provided on create.
func (u *CartsUpsertBulk) UpdateCompanyID() *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.UpdateCompanyID()
	})
}

// SetCompanyName sets the "company_name" field.
func (u *CartsUpsertBulk) SetCompanyName(v string) *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.SetCompanyName(v)
	})
}

// UpdateCompanyName sets the "company_name" field to the value that was provided on create.
func (u *CartsUpsertBulk) UpdateCompanyName() *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.UpdateCompanyName()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CartsUpsertBulk) SetCreatedAt(v time.Time) *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CartsUpsertBulk) UpdateCreatedAt() *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *CartsUpsertBulk) ClearCreatedAt() *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.ClearCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CartsUpsertBulk) SetUpdatedAt(v time.Time) *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CartsUpsertBulk) UpdateUpdatedAt() *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *CartsUpsertBulk) ClearUpdatedAt() *CartsUpsertBulk {
	return u.Update(func(s *CartsUpsert) {
		s.ClearUpdatedAt()
	})
}

// Exec executes the query.
func (u *CartsUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CartsCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CartsCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CartsUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
