// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"user/internal/ent/carts"
	"user/internal/ent/predicate"
)

// CartsUpdate is the builder for updating Carts entities.
type CartsUpdate struct {
	config
	hooks     []Hook
	mutation  *CartsMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CartsUpdate builder.
func (_u *CartsUpdate) Where(ps ...predicate.Carts) *CartsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CartsUpdate) SetUserID(v int64) *CartsUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CartsUpdate) SetNillableUserID(v *int64) *CartsUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CartsUpdate) AddUserID(v int64) *CartsUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *CartsUpdate) SetProductID(v int64) *CartsUpdate {
	_u.mutation.ResetProductID()
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *CartsUpdate) SetNillableProductID(v *int64) *CartsUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// AddProductID adds value to the "product_id" field.
func (_u *CartsUpdate) AddProductID(v int64) *CartsUpdate {
	_u.mutation.AddProductID(v)
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *CartsUpdate) SetQuantity(v int) *CartsUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *CartsUpdate) SetNillableQuantity(v *int) *CartsUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *CartsUpdate) AddQuantity(v int) *CartsUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CartsUpdate) SetStatus(v int) *CartsUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CartsUpdate) SetNillableStatus(v *int) *CartsUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *CartsUpdate) AddStatus(v int) *CartsUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *CartsUpdate) ClearStatus() *CartsUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetCompanyID sets the "company_id" field.
func (_u *CartsUpdate) SetCompanyID(v int64) *CartsUpdate {
	_u.mutation.ResetCompanyID()
	_u.mutation.SetCompanyID(v)
	return _u
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (_u *CartsUpdate) SetNillableCompanyID(v *int64) *CartsUpdate {
	if v != nil {
		_u.SetCompanyID(*v)
	}
	return _u
}

// AddCompanyID adds value to the "company_id" field.
func (_u *CartsUpdate) AddCompanyID(v int64) *CartsUpdate {
	_u.mutation.AddCompanyID(v)
	return _u
}

// SetCompanyName sets the "company_name" field.
func (_u *CartsUpdate) SetCompanyName(v string) *CartsUpdate {
	_u.mutation.SetCompanyName(v)
	return _u
}

// SetNillableCompanyName sets the "company_name" field if the given value is not nil.
func (_u *CartsUpdate) SetNillableCompanyName(v *string) *CartsUpdate {
	if v != nil {
		_u.SetCompanyName(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CartsUpdate) SetCreatedAt(v time.Time) *CartsUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CartsUpdate) SetNillableCreatedAt(v *time.Time) *CartsUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *CartsUpdate) ClearCreatedAt() *CartsUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CartsUpdate) SetUpdatedAt(v time.Time) *CartsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *CartsUpdate) SetNillableUpdatedAt(v *time.Time) *CartsUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *CartsUpdate) ClearUpdatedAt() *CartsUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// Mutation returns the CartsMutation object of the builder.
func (_u *CartsUpdate) Mutation() *CartsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CartsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CartsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CartsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CartsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CartsUpdate) check() error {
	if v, ok := _u.mutation.CompanyName(); ok {
		if err := carts.CompanyNameValidator(v); err != nil {
			return &ValidationError{Name: "company_name", err: fmt.Errorf(`ent: validator failed for field "Carts.company_name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CartsUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CartsUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CartsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(carts.Table, carts.Columns, sqlgraph.NewFieldSpec(carts.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(carts.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(carts.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(carts.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProductID(); ok {
		_spec.AddField(carts.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(carts.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(carts.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(carts.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(carts.FieldStatus, field.TypeInt, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(carts.FieldStatus, field.TypeInt)
	}
	if value, ok := _u.mutation.CompanyID(); ok {
		_spec.SetField(carts.FieldCompanyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCompanyID(); ok {
		_spec.AddField(carts.FieldCompanyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CompanyName(); ok {
		_spec.SetField(carts.FieldCompanyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(carts.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(carts.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(carts.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(carts.FieldUpdatedAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carts.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CartsUpdateOne is the builder for updating a single Carts entity.
type CartsUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CartsMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (_u *CartsUpdateOne) SetUserID(v int64) *CartsUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CartsUpdateOne) SetNillableUserID(v *int64) *CartsUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CartsUpdateOne) AddUserID(v int64) *CartsUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *CartsUpdateOne) SetProductID(v int64) *CartsUpdateOne {
	_u.mutation.ResetProductID()
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *CartsUpdateOne) SetNillableProductID(v *int64) *CartsUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// AddProductID adds value to the "product_id" field.
func (_u *CartsUpdateOne) AddProductID(v int64) *CartsUpdateOne {
	_u.mutation.AddProductID(v)
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *CartsUpdateOne) SetQuantity(v int) *CartsUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *CartsUpdateOne) SetNillableQuantity(v *int) *CartsUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *CartsUpdateOne) AddQuantity(v int) *CartsUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CartsUpdateOne) SetStatus(v int) *CartsUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CartsUpdateOne) SetNillableStatus(v *int) *CartsUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *CartsUpdateOne) AddStatus(v int) *CartsUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *CartsUpdateOne) ClearStatus() *CartsUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetCompanyID sets the "company_id" field.
func (_u *CartsUpdateOne) SetCompanyID(v int64) *CartsUpdateOne {
	_u.mutation.ResetCompanyID()
	_u.mutation.SetCompanyID(v)
	return _u
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (_u *CartsUpdateOne) SetNillableCompanyID(v *int64) *CartsUpdateOne {
	if v != nil {
		_u.SetCompanyID(*v)
	}
	return _u
}

// AddCompanyID adds value to the "company_id" field.
func (_u *CartsUpdateOne) AddCompanyID(v int64) *CartsUpdateOne {
	_u.mutation.AddCompanyID(v)
	return _u
}

// SetCompanyName sets the "company_name" field.
func (_u *CartsUpdateOne) SetCompanyName(v string) *CartsUpdateOne {
	_u.mutation.SetCompanyName(v)
	return _u
}

// SetNillableCompanyName sets the "company_name" field if the given value is not nil.
func (_u *CartsUpdateOne) SetNillableCompanyName(v *string) *CartsUpdateOne {
	if v != nil {
		_u.SetCompanyName(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CartsUpdateOne) SetCreatedAt(v time.Time) *CartsUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CartsUpdateOne) SetNillableCreatedAt(v *time.Time) *CartsUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *CartsUpdateOne) ClearCreatedAt() *CartsUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CartsUpdateOne) SetUpdatedAt(v time.Time) *CartsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *CartsUpdateOne) SetNillableUpdatedAt(v *time.Time) *CartsUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *CartsUpdateOne) ClearUpdatedAt() *CartsUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// Mutation returns the CartsMutation object of the builder.
func (_u *CartsUpdateOne) Mutation() *CartsMutation {
	return _u.mutation
}

// Where appends a list predicates to the CartsUpdate builder.
func (_u *CartsUpdateOne) Where(ps ...predicate.Carts) *CartsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CartsUpdateOne) Select(field string, fields ...string) *CartsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Carts entity.
func (_u *CartsUpdateOne) Save(ctx context.Context) (*Carts, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CartsUpdateOne) SaveX(ctx context.Context) *Carts {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CartsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CartsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CartsUpdateOne) check() error {
	if v, ok := _u.mutation.CompanyName(); ok {
		if err := carts.CompanyNameValidator(v); err != nil {
			return &ValidationError{Name: "company_name", err: fmt.Errorf(`ent: validator failed for field "Carts.company_name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CartsUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CartsUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CartsUpdateOne) sqlSave(ctx context.Context) (_node *Carts, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(carts.Table, carts.Columns, sqlgraph.NewFieldSpec(carts.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Carts.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, carts.FieldID)
		for _, f := range fields {
			if !carts.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != carts.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(carts.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(carts.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(carts.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProductID(); ok {
		_spec.AddField(carts.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(carts.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(carts.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(carts.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(carts.FieldStatus, field.TypeInt, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(carts.FieldStatus, field.TypeInt)
	}
	if value, ok := _u.mutation.CompanyID(); ok {
		_spec.SetField(carts.FieldCompanyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCompanyID(); ok {
		_spec.AddField(carts.FieldCompanyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CompanyName(); ok {
		_spec.SetField(carts.FieldCompanyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(carts.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(carts.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(carts.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(carts.FieldUpdatedAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Carts{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carts.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
