// Code generated by ent, DO NOT EDIT.

//go:build tools
// +build tools

// Package internal holds a loadable version of the latest schema.
package internal

const Schema = "{\"Schema\":\"user/internal/ent/schema\",\"Package\":\"user/internal/ent\",\"Schemas\":[{\"name\":\"User\",\"config\":{\"Table\":\"\"},\"fields\":[{\"name\":\"id\",\"type\":{\"Type\":13,\"Ident\":\"\",\"PkgPath\":\"\",\"PkgName\":\"\",\"Nillable\":false,\"RType\":null},\"tag\":\"json:\\\"id\\\"\",\"unique\":true,\"immutable\":true,\"position\":{\"Index\":0,\"MixedIn\":false,\"MixinIndex\":0},\"comment\":\"ID\"},{\"name\":\"nick_name\",\"type\":{\"Type\":13,\"Ident\":\"\",\"PkgPath\":\"\",\"PkgName\":\"\",\"Nillable\":false,\"RType\":null},\"tag\":\"json:\\\"nick_name\\\"\",\"position\":{\"Index\":1,\"MixedIn\":false,\"MixinIndex\":0},\"comment\":\"用户名称\"}],\"annotations\":{\"EntSQL\":{\"table\":\"User\"}}}],\"Features\":[\"intercept\",\"privacy\",\"schema/snapshot\",\"sql/lock\",\"sql/upsert\",\"sql/modifier\",\"sql/execquery\"]}"
