// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CartsColumns holds the columns for the "carts" table.
	CartsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "cart_id", Type: field.TypeInt64, Unique: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "product_id", Type: field.TypeInt64},
		{Name: "quantity", Type: field.TypeInt, Default: 1},
		{Name: "status", Type: field.TypeInt, Nullable: true, Default: 1},
		{Name: "company_id", Type: field.TypeInt64},
		{Name: "company_name", Type: field.TypeString, Size: 255},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
	}
	// CartsTable holds the schema information for the "carts" table.
	CartsTable = &schema.Table{
		Name:       "carts",
		Columns:    CartsColumns,
		PrimaryKey: []*schema.Column{CartsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CartsTable,
	}
)

func init() {
	CartsTable.Annotation = &entsql.Annotation{
		Table: "carts",
	}
}
